FROM --platform=linux/amd64 ubuntu:22.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential cmake mesa-common-dev libxext-dev libtcc-dev clang

COPY . /repo
WORKDIR /repo/dev/build
RUN cmake .. -DCMAKE_INSTALL_PREFIX=/install
RUN make -j8
RUN make install
RUN clang++ /repo/mayhem/fuzz_to_string_conv.cpp -fsanitize=fuzzer,address -I /repo/dev/src/lobster/ -std=c++17 -I /repo/dev/include/ -o /fuzz

FROM ubuntu:22.04 as package
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y mesa-common-dev 
COPY --from=builder /install /install
COPY --from=builder /fuzz /fuzz_to_string_conv
